server:
  port: 3030
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: temporal-samples
  # temporal specific configs
  #temporal:
  #  namespace: default
    #connection:
    #  target: 127.0.0.1:7233
    # (Note following configuration are not set by default but serve more as reference)
    #    workers:
    #      - task-queue: DemoTaskQueue
    #        capacity:
    #          max-concurrent-workflow-task-pollers: 6
    #          max-concurrent-activity-task-pollers: 6
    #        rate-limits:
    #          max-worker-activities-per-second: 3
    #          max-task-queue-activities-per-second: 3
    #    workflow-cache:
    #      max-instances: 10
    #      max-threads: 10
#    workersAutoDiscovery:
#      packages: com.antmendoza.temporal.workflow

springdoc:
  api-docs:
    path: /v3/api-docs

springfox:
  documentation:
    swagger-ui:
      enabled: true